FROM openresty/openresty:alpine

RUN apk add --no-cache \
    build-base \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    gcc \
    libc-dev \
    make \
    curl \
    perl-dev \
    postgresql-dev

RUN curl -L https://openresty.org/download/openresty-1.19.9.1.tar.gz -o openresty.tar.gz && \
    tar xzf openresty.tar.gz && \
    cd openresty-1.19.9.1 && \
    ./configure --prefix=/opt/openresty \
                --with-pcre-jit \
                --with-ipv6 \
                --without-http_redis2_module \
                --with-http_iconv_module \
                --with-http_postgres_module \
                -j8 && \
    make && \
    make install

RUN rm -rf /var/cache/apk/* /tmp/* /var/tmp/* openresty.tar.gz openresty-1.19.9.1

# Set the default command to run Nginx
CMD ["/opt/openresty/nginx/sbin/nginx", "-g", "daemon off;"]

# Expose ports
EXPOSE 80 443
